---
name: Validate package definitions
description: Validate mason-registry package definitions.

inputs:
  packages:
    required: true
    description: The packages to test (space separated string).

runs:
  using: composite
  steps:
    - shell: bash
      run: $GITHUB_ACTION_PATH/validate.sh
      env:
        PACKAGES: ${{ inputs.packages }}
